// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5BKIU0hM7IR4Yi6M7VbOWEEq-1XiIhBI',
    appId: '1:349259493121:web:9773cbd39c22f404163500',
    messagingSenderId: '349259493121',
    projectId: 'foot-app-3d3f0',
    authDomain: 'foot-app-3d3f0.firebaseapp.com',
    storageBucket: 'foot-app-3d3f0.firebasestorage.app',
    measurementId: 'G-QH4B45B2TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgTv-hqjDmGEnlQsWcrS_6bl_xlFSUgCM',
    appId: '1:349259493121:android:304433472593f62a163500',
    messagingSenderId: '349259493121',
    projectId: 'foot-app-3d3f0',
    storageBucket: 'foot-app-3d3f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCBxSVNF8Aob3zne20XQCBYof-3rCb9is',
    appId: '1:349259493121:ios:1bb36a512da00e6c163500',
    messagingSenderId: '349259493121',
    projectId: 'foot-app-3d3f0',
    storageBucket: 'foot-app-3d3f0.firebasestorage.app',
    iosBundleId: 'com.foot.app.footApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCBxSVNF8Aob3zne20XQCBYof-3rCb9is',
    appId: '1:349259493121:ios:1bb36a512da00e6c163500',
    messagingSenderId: '349259493121',
    projectId: 'foot-app-3d3f0',
    storageBucket: 'foot-app-3d3f0.firebasestorage.app',
    iosBundleId: 'com.foot.app.footApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5BKIU0hM7IR4Yi6M7VbOWEEq-1XiIhBI',
    appId: '1:349259493121:web:b23b5a388e61efb0163500',
    messagingSenderId: '349259493121',
    projectId: 'foot-app-3d3f0',
    authDomain: 'foot-app-3d3f0.firebaseapp.com',
    storageBucket: 'foot-app-3d3f0.firebasestorage.app',
    measurementId: 'G-KZH16TBY3Q',
  );
}
